[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.7"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  branch = "teams"
  name = "github.com/russellcardullo/go-pingdom"
  source = "https://github.com/kevinburkenotion/go-pingdom.git"

[prune]
  go-tests = true
  unused-packages = true
